#!/bin/bash

[ -f /var/lib/bitmarkd/peer.public ] && rm -r /var/lib/bitmarkd/peer.*
[ -f /var/lib/bitmarkd/rpc.crt ] && rm -r /var/lib/bitmarkd/rpc.*
[ -f /var/lib/bitmarkd/proof.public ] && rm -r /var/lib/bitmarkd/proof.*

/usr/sbin/bitmarkd --config-file /etc/bitmarkd.conf gen-peer-identity /var/lib/bitmarkd/
/usr/sbin/bitmarkd --config-file /etc/bitmarkd.conf gen-rpc-cert /var/lib/bitmarkd/
/usr/sbin/bitmarkd --config-file /etc/bitmarkd.conf gen-proof-identity /var/lib/bitmarkd/

chown bitmarkd:bitmarkd -R /var/lib/bitmarkd
