# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13
        environment:
          - GO111MODULE: "on"

    working_directory: /go/src/github.com/bitmark-inc/bitmarkd
    steps:
      - checkout
      - run: sudo sh -c 'mkdir -p /etc/apt/source.list.d/'
      - run:
          name: Add repo testing
          command: |
            sudo sh -c 'echo "deb http://ftp.de.debian.org/debian/ testing main contrib non-free" >> /etc/apt/sources.list.d/testing.list'
            sudo sh -c 'echo "deb-src http://ftp.de.debian.org/debian/ testing main contrib non-free" >> /etc/apt/sources.list.d/testing.list'
            sudo sh -c 'echo "deb http://security.debian.org/ testing/updates  main contrib non-free" >> /etc/apt/source.list.d/testing.list'
      - run:
          name: Add repo stable 
          command: |
            sudo sh -c 'echo "deb http://ftp.de.debian.org/debian/ stable main contrib non-free" >> /etc/apt/sources.list.d/stable.list'
            sudo sh -c 'echo "deb-src http://ftp.de.debian.org/debian/ stable main contrib non-free" >> /etc/apt/sources.list.d/stable.list'
            sudo sh -c 'echo "deb http://security.debian.org/ stable/updates  main contrib non-free" >> /etc/apt/source.list.d/stable.list'
      - run:
          name: Prepare environment
          command: |
            sudo apt-get update
            sudo apt-get -t testing install libargon2-1 libargon2-dev
            sudo apt-get install uuid-dev libzmq3-dev wget
            sudo apt-get -t testing install pkg-config
      - run:
          name: Get misspell
          command: |
             wget https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz
             tar -xpvf misspell_0.3.4_linux_64bit.tar.gz
      - run:
          name: Get gosec
          command: |
             wget https://github.com/securego/gosec/releases/download/v2.1.0/gosec_2.1.0_linux_amd64.tar.gz
             tar -xpvf gosec_2.1.0_linux_amd64.tar.gz
      - run:
          name: Get golangcli-lint
          command: |
             wget https://github.com/golangci/golangci-lint/releases/download/v1.21.0/golangci-lint-1.21.0-linux-amd64.tar.gz
             tar -xpvf golangci-lint-1.21.0-linux-amd64.tar.gz
             mv golangci-lint-1.21.0-linux-amd64/golangci-lint .
      - run:
          name: Get golint
          command: go get -v golang.org/x/lint/golint
      - run:
          name: Run golint
          command: golint ./...
      - run:
          name: run misspell
          command: ./misspell ./...
      - run:
          name: Run gosec
          command: ./gosec -exclude=G104,G204,G402,G304 ./...
      - run:
          name: Run golangcli-lint
          command: ./golangci-lint run --no-config --disable=ineffassign,errcheck,govet
