// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2pMessage.proto

package p2p

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type P2PMessage struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PMessage) Reset()         { *m = P2PMessage{} }
func (m *P2PMessage) String() string { return proto.CompactTextString(m) }
func (*P2PMessage) ProtoMessage()    {}
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a259f8162cba2831, []int{0}
}

func (m *P2PMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PMessage.Unmarshal(m, b)
}
func (m *P2PMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PMessage.Marshal(b, m, deterministic)
}
func (m *P2PMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage.Merge(m, src)
}
func (m *P2PMessage) XXX_Size() int {
	return xxx_messageInfo_P2PMessage.Size(m)
}
func (m *P2PMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage proto.InternalMessageInfo

func (m *P2PMessage) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BusMessage struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Parameters           [][]byte `protobuf:"bytes,2,rep,name=Parameters,proto3" json:"Parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusMessage) Reset()         { *m = BusMessage{} }
func (m *BusMessage) String() string { return proto.CompactTextString(m) }
func (*BusMessage) ProtoMessage()    {}
func (*BusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a259f8162cba2831, []int{1}
}

func (m *BusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusMessage.Unmarshal(m, b)
}
func (m *BusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusMessage.Marshal(b, m, deterministic)
}
func (m *BusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusMessage.Merge(m, src)
}
func (m *BusMessage) XXX_Size() int {
	return xxx_messageInfo_BusMessage.Size(m)
}
func (m *BusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BusMessage proto.InternalMessageInfo

func (m *BusMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *BusMessage) GetParameters() [][]byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// to parse Listeners parameter from announce module
type Addrs struct {
	Address              [][]byte `protobuf:"bytes,1,rep,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addrs) Reset()         { *m = Addrs{} }
func (m *Addrs) String() string { return proto.CompactTextString(m) }
func (*Addrs) ProtoMessage()    {}
func (*Addrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a259f8162cba2831, []int{2}
}

func (m *Addrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addrs.Unmarshal(m, b)
}
func (m *Addrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addrs.Marshal(b, m, deterministic)
}
func (m *Addrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addrs.Merge(m, src)
}
func (m *Addrs) XXX_Size() int {
	return xxx_messageInfo_Addrs.Size(m)
}
func (m *Addrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Addrs.DiscardUnknown(m)
}

var xxx_messageInfo_Addrs proto.InternalMessageInfo

func (m *Addrs) GetAddress() [][]byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type MockProtoMessage struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MockProtoMessage) Reset()         { *m = MockProtoMessage{} }
func (m *MockProtoMessage) String() string { return proto.CompactTextString(m) }
func (*MockProtoMessage) ProtoMessage()    {}
func (*MockProtoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a259f8162cba2831, []int{3}
}

func (m *MockProtoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockProtoMessage.Unmarshal(m, b)
}
func (m *MockProtoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockProtoMessage.Marshal(b, m, deterministic)
}
func (m *MockProtoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockProtoMessage.Merge(m, src)
}
func (m *MockProtoMessage) XXX_Size() int {
	return xxx_messageInfo_MockProtoMessage.Size(m)
}
func (m *MockProtoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MockProtoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MockProtoMessage proto.InternalMessageInfo

func (m *MockProtoMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*P2PMessage)(nil), "main.P2PMessage")
	proto.RegisterType((*BusMessage)(nil), "main.BusMessage")
	proto.RegisterType((*Addrs)(nil), "main.Addrs")
	proto.RegisterType((*MockProtoMessage)(nil), "main.MockProtoMessage")
}

func init() { proto.RegisterFile("p2pMessage.proto", fileDescriptor_a259f8162cba2831) }

var fileDescriptor_a259f8162cba2831 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x30, 0x2a, 0xf0,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d,
	0xcc, 0xcc, 0x53, 0x52, 0xe0, 0xe2, 0x0a, 0x30, 0x0a, 0x80, 0xca, 0x08, 0x09, 0x71, 0xb1, 0xb8,
	0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x04, 0x81, 0xd9, 0x4a, 0x6e, 0x5c, 0x5c,
	0x4e, 0xa5, 0xc5, 0x30, 0x15, 0x12, 0x5c, 0xec, 0xc9, 0xf9, 0xb9, 0xb9, 0x89, 0x79, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x1c, 0x17, 0x57, 0x40, 0x62, 0x51, 0x62,
	0x6e, 0x6a, 0x49, 0x6a, 0x51, 0xb1, 0x04, 0x13, 0xd8, 0x04, 0x24, 0x11, 0x25, 0x45, 0x2e, 0x56,
	0xc7, 0x94, 0x94, 0xa2, 0x62, 0x90, 0x11, 0x20, 0x46, 0x6a, 0x71, 0x31, 0xd4, 0x1e, 0x18, 0x57,
	0x49, 0x8d, 0x4b, 0xc0, 0x37, 0x3f, 0x39, 0x3b, 0x00, 0xe4, 0x3e, 0x4c, 0x27, 0x81, 0x6c, 0x03,
	0xb3, 0x93, 0xd8, 0xc0, 0x3e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x76, 0x21, 0x64,
	0xd5, 0x00, 0x00, 0x00,
}
