#!/bin/sh
# simple display of network main nodes

ERROR() {
  printf 'error: '
  printf "${@}"
  printf '\n'
  exit 1
}

VERBOSE() {
  [ X"${verbose}" = X"no" ] && return 0
  printf "${@}"
  printf '\n'
}

USAGE() {
  if [ -n "${1}" ]
  then
    printf 'error: '
    printf "${@}"
    printf '\n'
  fi
  echo usage: "${0##*/}" '[options] [start [finish]]'
  echo '       --help             -h            this message'
  echo '       --verbose          -v            more messages'
  echo '       --compact          -c            squash output'
  echo '       --network=NET      -n NET        network {live|test} ['"${network}"']'
  echo '       --debug            -D            debuging messages'
  exit 1
}

# main program
verbose=no
debug=no
compact=no
network=testing

# parse options
while getopts :hvcn:D-: option
do
  # convert long options
  if [ X"${option}" = X"-" ]
  then
    option="${OPTARG%%=*}"
    OPTARG="${OPTARG#${option}}"
    OPTARG="${OPTARG#=}"
  fi
  case "${option}" in
    (v|verbose)
      verbose=yes
      ;;

    (c|compact)
      compact=yes
      ;;

    (n|network)
      case "${OPTARG}" in
        (l|live|b|bitmark)
          network=bitmark
          ;;
        (t|test|testing)
          network=testing
          ;;
        (*)
          USAGE 'invalid network: "%s"' "${OPTARG}"
          ;;
      esac
      ;;

    (--)
      break
      ;;

    (D|debug)
      debug=yes
      ;;

    (h|help)
      USAGE
      ;;

    ('?')
      USAGE 'invalid option: -%s' "${OPTARG}"
      ;;

    (*)
      USAGE 'invalid option: --%s' "${option}"
      ;;
  esac
done

shift $((OPTIND - 1))

# verify arguments
#[ ${#} -ne 0 ] && USAGE 'extraneous arguments: %s' "${*}"
[ $# -gt 2 ] && USAGE 'invalid extraneous arguments: %s' "${*}"
[ $# -lt 2 ] && USAGE 'insufficient arguments: %s' "${*}"

# enable debugging
[ X"${debug}" = X"yes" ] && set -x


start="${1}"
finish="${2}"

[ -z "${start}" ] && start=0
[ -z "${finish}" ] && finish=11


# formatted
if [ X"${compact}" = X"yes" ]
then
  compact_b=''
  compact_m='1'
  compact_ch='1'
  compact_sw=''
  compact_v='11'
  compact_up=''
else
  compact_b='b: '
  compact_m='6'
  compact_ch=''
  compact_sw='sw: '
  compact_v='14'
  compact_up='up: '
fi

filter='
    def rj($f;$w): ("                    "+($f|tostring))[-$w:];
    def lj($f;$w): (($f|tostring)+"                    ")[:$w];
    "\u001b[1;32m" + lj(._connection;7) + " " +
    "\u001b[1;32m'"${compact_b}"'\u001b[1;33m" + (.block.height // .blocks | tostring) +
    "\u001b[0;33m " + (.block.hash[56:64] // "--------") +
    " \u001b[" + (if .mode=="Normal" then "1;32" else "0;31" end) + "m" + .mode[0:'"${compact_m}"'] +
    " \u001b[0;36m" + .chain[0:'"${compact_ch}"'] +
    " \u001b[1;34mp:\u001b[1;34m" + rj(.transactionCounters.pending;5) +
    " \u001b[1;31mv:\u001b[1;31m " + rj(.transactionCounters.verified;5) +
    " \u001b[1;34mc:" + rj(.peers|tostring;3) +
    " \u001b[1;35m'"${compact_sw}"'" + lj(.version;'"${compact_v}"') +
    " \u001b[0;37m'"${compact_up}"'" + rj(.uptime|tostring
           | sub("[[:digit:]]+[.][[:digit:]]*s$";"")
           | sub("^(?<a>[[:digit:]]+m)";"0h\(.a)")
           | sub("h(?<a>[^m]*)m.*$";":\(.a)")
           | sub(":(?<a>.)$";":0\(.a)");8) +
    "\u001b[0m"
'

#filter='.'

# loop through all nodes
for i in $(seq "${start}" "${finish}")
do
  if ! r="$(bitmark-cli --network="${network}" --connection="${i}" bitmarkd 2>&1)"
  then
    printf 'conn %2d: %s\n' "${i}" "${r}"
  else
    printf '%s' "${r}" | jq --raw-output "${filter}"
  fi
done
